
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed8;

	private global::Gtk.Button DesniGumb;

	private global::Gtk.Button LeviGumb;

	private global::Gtk.Label label2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed8 = new global::Gtk.Fixed();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.DesniGumb = new global::Gtk.Button();
		this.DesniGumb.CanFocus = true;
		this.DesniGumb.Name = "DesniGumb";
		this.DesniGumb.UseUnderline = true;
		this.DesniGumb.Label = global::Mono.Unix.Catalog.GetString("Desni");
		this.fixed8.Add(this.DesniGumb);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.DesniGumb]));
		w1.X = 294;
		w1.Y = 130;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.LeviGumb = new global::Gtk.Button();
		this.LeviGumb.CanFocus = true;
		this.LeviGumb.Name = "LeviGumb";
		this.LeviGumb.UseUnderline = true;
		this.LeviGumb.Label = global::Mono.Unix.Catalog.GetString("Levi");
		this.fixed8.Add(this.LeviGumb);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.LeviGumb]));
		w2.X = 59;
		w2.Y = 130;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.fixed8.Add(this.label2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.label2]));
		w3.X = 193;
		w3.Y = 141;
		this.Add(this.fixed8);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 419;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.DesniGumb.Pressed += new global::System.EventHandler(this.DesniPritinjen);
		this.DesniGumb.Released += new global::System.EventHandler(this.DesniSpuscen);
		this.LeviGumb.Pressed += new global::System.EventHandler(this.LeviPritisnjen);
		this.LeviGumb.Released += new global::System.EventHandler(this.LeviSpuscen);
	}
}
